apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 876594438092.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlemusic:91599a5935b6e3656c742553dd29bd96f7e8d8c8
        ports:
        - containerPort: 80
