apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 876594438092.dkr.ecr.us-west-2.amazonaws.com/shopping-site-computers:904076934cd0cd9ad4c6766b4dcace9963b0ea21
        ports:
        - containerPort: 80
