apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 876594438092.dkr.ecr.us-west-2.amazonaws.com/shopping-site-computers:91599a5935b6e3656c742553dd29bd96f7e8d8c8
        ports:
        - containerPort: 80
