apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 876594438092.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlegrocery:a1697aa77213aa2a1ac56af2f3f8c5098291dfb3
        ports:
        - containerPort: 80
